<a href="https://colab.research.google.com/github/minessy/Mec-nica-dos-S-lidos-1/blob/main/trabalho_pr%C3%A1tico_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a)

In [ ]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})

def versor(v1,v2,v3): return np.array([v1,v2,v3])

n1 = versor(0.373239,0.653484,0.658522)
n2 = versor(-0.653484,-0.318654,0.686599)
n3 = versor(0.658522,-0.686599,0.308108)

print('n1 = ',n1)
print('n2 = ',n2)
print('n3 = ',n3)

n1 =  [ 0.373239  0.653484  0.658522]
n2 =  [-0.653484 -0.318654  0.686599]
n3 =  [ 0.658522 -0.686599  0.308108]


Ortonormalidade

In [ ]:
print('i = j: ')
print(f'np.dot(n1,n1) = {np.dot(n1,n1):.1f}')
print(f'np.dot(n2,n2) = {np.dot(n2,n2):.1f}')
print(f'np.dot(n3,n3) = {np.dot(n3,n3):.1f}')

i = j: 
np.dot(n1,n1) = 1.0
np.dot(n2,n2) = 1.0
np.dot(n3,n3) = 1.0


Ortogonalidade

In [ ]:
print('i ne j: ')
print(f'np.dot(n2,n3) = {np.dot(n2,n3):.1f}')
print(f'np.dot(n1,n3) = {np.dot(n1,n3):.1f}')
print(f'np.dot(n1,n2) = {np.dot(n1,n2):.1f}')

i ne j: 
np.dot(n2,n3) = 0.0
np.dot(n1,n3) = 0.0
np.dot(n1,n2) = -0.0


como os vetores são ortogonais e ortonormados dá certo

Aij

In [ ]:
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})

def trans01(i0i1,i0j1,i0k1,j0i1,j0j1,j0k1,k0i1,k0j1,k0k1):
    linha0 = [i0i1,j0i1,k0i1]
    linha1 = [i0j1,j0j1,k0j1]
    linha2 = [i0k1,j0k1,k0k1]
    return np.array([linha0,linha1,linha2])

Aij = trans01(n1[0],n2[0],n3[0],n1[1],n2[1],n3[1],n1[2],n2[2],n3[2])
print(f'\n Matriz de mudanca de base de S0 para S1: \n Aij = \n {Aij}')


 Matriz de mudanca de base de S0 para S1: 
 Aij = 
 [[ 0.373239  0.653484  0.658522]
 [-0.653484 -0.318654  0.686599]
 [ 0.658522 -0.686599  0.308108]]


verificação do Aij

In [ ]:
print('[Aij^T][Aij] = [I] = \n',np.dot(np.transpose(Aij),Aij))
print('\n det([Aij]) = ','{: 0.1f}'.format(np.linalg.det(Aij)))

[Aij^T][Aij] = [I] = 
 [[ 1.000000  0.000000  0.000001]
 [ 0.000000  1.000000 -0.000001]
 [ 0.000001 -0.000001  1.000000]]

 det([Aij]) =   1.0


sigma'

In [ ]:
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})

S0tn1 = np.array([[16.413],[1.575],[0]])
S0tn2 = np.array([[-27.193],[-1.650],[0]])
S0tn3 = np.array([[25.518],[0.310],[0]])
print('Componentes dos vetores tensao no referencial S0 :')
print('t(n1).S0 | t(n2).S0 | t(n3).S0')
for i in range(0,3):
    print(S0tn1[i],' ',S0tn2[i],' ',S0tn2[i])

Componentes dos vetores tensao no referencial S0 :
t(n1).S0 | t(n2).S0 | t(n3).S0
[ 16.41300]   [-27.19300]   [-27.19300]
[ 1.57500]   [-1.65000]   [-1.65000]
[ 0.00000]   [ 0.00000]   [ 0.00000]


In [ ]:
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})
S1tn1 = np.dot(Aij,S0tn1)
S1tn2 = np.dot(Aij,S0tn2)
S1tn3 = np.dot(Aij,S0tn3)

print('Componentes dos vetores tensao no referencial S1 :')
print('tn1.S1 | tn2.S1 | tn3.S1')
for i in range(0,3):
    print(S1tn1[i],' ',S1tn2[i],' ',S1tn2[i])

Componentes dos vetores tensao no referencial S1 :
tn1.S1 | tn2.S1 | tn3.S1
[ 7.15521]   [-11.22774]   [-11.22774]
[-11.22751]   [ 18.29597]   [ 18.29597]
[ 9.72693]   [-16.77430]   [-16.77430]


In [ ]:
sigma1 = np.hstack((S1tn1,S1tn2,S1tn3))
print('sigma1 = \n', sigma1)

sigma1 = 
 [[ 7.15521 -11.22774  9.72689]
 [-11.22751  18.29597 -16.77439]
 [ 9.72693 -16.77430  16.59132]]


B)

In [ ]:
Aji = np.transpose(Aij)
sigma0 = np.dot(Aji, np.dot(sigma1, np.transpose(Aji)))
print('\nsigma0 = \n', sigma0)



sigma0 = 
 [[ 40.70032  1.87016 -0.00007]
 [ 1.87026  1.34217 -0.00020]
 [ 0.00002  0.00000  0.00000]]


c) depois verificamos este código com mais cuidado

In [ ]:
from sympy.solvers import solve
from sympy import symbols


d1,d2,d3 = symbols('d1 d2 d3')

def eq1(d1,d2,d3,vp): return (sigma0[0,0] - vp)*d1 + sigma0[0,1]*d2 + sigma0[0,2]*d3
def eq2(d1,d2,d3,vp): return sigma0[1,0]*d1 + (sigma0[1,1] - vp)*d2 + sigma0[1,2]*d3
def eq3(d1,d2,d3,vp): return sigma0[2,0]*d1 + sigma0[2,1]*d2 + (sigma0[2,2] - vp)*d3
def eq4(d1,d2,d3): return d1**2 + d2**2 + d3**2 - 1

def versor(e1,e2,e3): return np.array([e1,e2,e3])


print('\n Calculo dos invariantes pela matriz das tensões  : ............................')

I1 = np.trace(sigma0)
print('1º Invariante, I1:', '{:.6f}'.format(I1))

I2 = 0.5*(np.trace(sigma0)**2 -np.trace(np.dot(sigma0,sigma0)))
print('2º Invariante, I2 :', '{:.6f}'.format(I2))

I3 = np.linalg.det(sigma0)
print('3º Invariante, I3 :', '{:.6f}'.format(I3))

print('\n Resolucao Simbolica - Sympy : ............................')
x = symbols('x')
def eqcar(x): return x**3 - I1*x**2 + I2*x - I3
print('\n Equacao carateristica:')
print(eqcar(x),' = 0')
valproprios = solve(eqcar(x), x, dict=True)
print('\n sol : ')
print(valproprios)
print('\n Resolucao Numerica - Numpy : ............................')
valpropriosN = np.roots([1,-I1,I2,-I3])
print('\n Roots = ',-np.sort(-valpropriosN))

print('\n Resolucao Analítica - Formula recursiva Poly3: ..........')
print('\n p(x) = x**3 + a x**2 + b*c + c = 0')
def frPoly3(a,b,c):
    p = b-a**2/3
    q = (2*a**3)/27 - (a*b)/3 + c
    DeltaPoly3 = q**2/4 + p**3/27
    print('\nDelta(Poly3) :', DeltaPoly3)
    if DeltaPoly3 < 0:
        print('existe três soluções reais')
        x1 = (2/np.sqrt(3))*np.sqrt(-p)*np.sin((1/3)*np.arcsin((3*np.sqrt(3)*q)/(2*np.sqrt(-p)**3))) - a/3
        x2 = -(2/np.sqrt(3))*np.sqrt(-p)*np.sin((1/3)*np.arcsin((3*np.sqrt(3)*q)/(2*np.sqrt(-p)**3)) + np.pi/3) - a/3
        x3 = (2/np.sqrt(3))*np.sqrt(-p)*np.cos((1/3)*np.arcsin((3*np.sqrt(3)*q)/(2*np.sqrt(-p)**3)) + np.pi/6) - a/3
    elif DeltaPoly3 == 0:
        print('existe três raízes repetidas')
        x1 = -2*(q/2)**(1/3) - a/3
        x2 = (q/2)**(1/3) - a/3
        x3 = x2
    else:
        print('existe apenas uma única solução real')
        x1 = (-q/2 + np.sqrt(DeltaPoly3))**(1/3) + (-q/2 - np.sqrt(DeltaPoly3))**(1/3) - a/3
        x2 = x1; x3 = x1

    return  np.array([x1,x2,x3])

valpropfrPoly3 = frPoly3(-I1,I2,-I3)
print('\n Formula recursiva Poly3 = ',-np.sort(-valpropfrPoly3))


 Calculo dos invariantes pela matriz das tensões  : ............................
1º Invariante, I1: 42.042495
2º Invariante, I2 : 51.129129
3º Invariante, I3 : -0.000000

 Resolucao Simbolica - Sympy : ............................

 Equacao carateristica:
x**3 - 42.0424952957483*x**2 + 51.1291290243797*x + 5.642358688587e-14  = 0

 sol : 
[{x: -1.10355071487656e-15 - 0.e-35*I}, {x: 1.25350312178128 - 0.e-21*I}, {x: 40.788992173967 - 0.e-21*I}]

 Resolucao Numerica - Numpy : ............................

 Roots =  [ 40.78899  1.25350 -0.00000]

 Resolucao Analítica - Formula recursiva Poly3: ..........

 p(x) = x**3 + a x**2 + b*c + c = 0

Delta(Poly3) : -37834.436023730785
existe três soluções reais

 Formula recursiva Poly3 =  [ 40.78899  1.25350 -0.00000]


d)Invariantes

In [ ]:
I1 = np.trace(sigma0)
print('1º Invariante, I1 :', '{:.6f}'.format(I1))

I2 = 0.5*(np.trace(sigma0)**2 -np.trace(np.dot(sigma0,sigma0)))
print('2º Invariante, I2 :', '{:.6f}'.format(I2))

I3 = np.linalg.det(sigma0)
print('2º Invariante, I3 :', '{:.6f}'.format(I3))


1º Invariante, I1 : 42.042495
2º Invariante, I2 : 51.129129
2º Invariante, I3 : -0.000000


Como temos a regra de que I1>I2>I3:

In [ ]:
sigmaI =np.array([[I2,0,0],[0,I1,0],[0,0,I3]])
print('sigmaI = \n', sigmaI)

sigmaI = 
 [[ 51.12913  0.00000  0.00000]
 [ 0.00000  42.04250  0.00000]
 [ 0.00000  0.00000 -0.00000]]


e)

In [ ]:
import numpy as np
sigma0 = np.dot(Aji, np.dot(sigma1, np.transpose(Aji)))
print('\nsigma0 = \n', sigma0)



sigma0 = 
 [[ 40.70032  1.87016 -0.00007]
 [ 1.87026  1.34217 -0.00020]
 [ 0.00002  0.00000  0.00000]]


In [ ]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})

def versor(v1,v2,v3): return np.array([v1,v2,v3])

v = versor(1/np.sqrt(2),0.653484,1/np.sqrt(2))

print('v = ', v)


v =  [ 0.707107  0.653484  0.707107]


In [ ]:
t=np.dot(v,sigma0)

print('t=', t)

t= [ 30.001675  2.199489 -0.000178]


In [ ]:
sigma_nor= np.dot(v,np.transpose(t))

print('sigma_nor (MPa) =',sigma_nor)

sigma_nor (MPa) = 22.65159244889814


In [ ]:
sigma_tan=np.sqrt(np.dot(t,t)+(sigma_nor)**2)

print('sigma_tan (Mpa) =', sigma_tan)

sigma_tan (Mpa) = 37.65677727760237
